name: Laravel

on:
  push:
    branches:
      - master
      - feature/**
      - fix/**
  pull_request:
    branches:
      - master
      - feature/**
      - fix/**

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp .env.test .env
    - name: Install Dependencies
      run: composer install 
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Setup Database
      # MySQL の起動とデータベースの作成
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'
    - name: Migration and Seeding
      run: php artisan migrate:fresh --seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      # phpunit.xml で DB_CONNECTION を testing を使用しているので合わせる
      env:
        DB_CONNECTION: mysql
        DB_TEST_HOST: 127.0.0.1
        DB_TEST_PORT: 3306
        DB_TEST_DATABASE: test
        DB_TEST_USERNAME: root
        DB_TEST_PASSWORD: root
      run: vendor/bin/phpunit
